@startuml casos-de-uso
title VetCare+ - Casos de Uso

left to right direction
skinparam packageStyle rectangle

actor Tutor
actor Recepcionista
actor Veterinario
actor Admin as "Administrador"

actor Pagamento as "Gateway Pagamento" <<externo>>
actor Email as "Servico de E-mail" <<externo>>

rectangle "VetCare+" {
  usecase UC1 as "Fazer login"
  usecase UC2 as "Cadastrar pet"
  usecase UC3 as "Ver prontuario do pet"
  usecase UC4 as "Agendar consulta"
  usecase UC5 as "Cancelar consulta"
  usecase UC6 as "Atender consulta"
  usecase UC7 as "Registrar prontuario"
  usecase UC8 as "Prescrever remedio"
  usecase UC9 as "Aplicar vacina"
  usecase UC10 as "Pagar consulta"
  usecase UC11 as "Enviar lembrete"
  usecase UC12 as "Gerenciar veterinarios"
  usecase UC13 as "Gerenciar servicos e precos"
  usecase UC14 as "Gerar relatorio financeiro"
}

Tutor --> UC1
Tutor --> UC2
Tutor --> UC3
Tutor --> UC4
Tutor --> UC5
Tutor --> UC10

Recepcionista --> UC1
Recepcionista --> UC4
Recepcionista --> UC5
Recepcionista --> UC10

Veterinario --> UC1
Veterinario --> UC6
Veterinario --> UC7
Veterinario --> UC8
Veterinario --> UC9

Admin --> UC1
Admin --> UC12
Admin --> UC13
Admin --> UC14

UC10 --> Pagamento
UC11 --> Email

UC4 ..> UC1 : <<include>>
UC5 ..> UC1 : <<include>>
UC6 ..> UC1 : <<include>>
UC10 ..> UC1 : <<include>>
UC7 ..> UC6 : <<include>>
UC8 .> UC6 : <<extend>>
UC9 .> UC6 : <<extend>>
UC11 .> UC4 : <<extend>>

@enduml
