@startuml componentes
title VetCare+ - Componentes / Arquitetura

skinparam componentStyle rectangle

actor Usuario

node "Navegador" {
  [SPA React + Vite] as SPA
}

node "Servidor (Docker)" {
  [Nginx] as Nginx

  package "API Spring Boot" {
    [Controller] as Ctrl
    [Service] as Svc
    [Repository (JPA)] as Repo
    [Security (JWT)] as Sec
    [DTO / Mapper] as DTO
  }

  database "PostgreSQL 16" as DB
}

cloud "Servicos externos" {
  [Gateway de Pagamento] as Pag
  [Servico de E-mail] as SMTP
}

Usuario --> SPA
SPA -- Nginx : HTTPS
Nginx --> Ctrl : /api/**
Ctrl --> Sec
Ctrl --> DTO
Ctrl --> Svc
Svc --> Repo
Repo --> DB : JDBC

Svc --> Pag : REST (HTTPS)
Svc --> SMTP : SMTP

@enduml
